### ISSUE TITLE
failed to lazily initialize a collection of role

### ISSUE THREAD

**Issue by midikang** [midikang/midi-petclinic-home#14]
failed to lazily initialize a collection of role: com.midi.samples.petclinic.model.Zone.locations, could not initialize proxy - no Session

**Comment by midikang** [comment]
### The log details:

```
17:34:02.356 [http-8080-1] DEBUG o.s.w.s.h.SimpleMappingExceptionResolver - Resolving exception from handler [public java.lang.String com.midi
.samples.petclinic.web.LocationController.initCreateForm(int,java.util.Map<java.lang.String, java.lang.Object>)]: org.hibernate.LazyInitializa
tionException: failed to lazily initialize a collection of role: com.midi.samples.petclinic.model.Zone.locations, could not initialize proxy -
 no Session
17:34:02.449 [http-8080-1] WARN  warn - Handler execution resulted in exception
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.midi.samples.petclinic.model.Zone.locations,
could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:5
75) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:214)
~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
        at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:155) ~[hibernate-core-4.3
.10.Final.jar:4.3.10.Final]
        at org.hibernate.collection.internal.PersistentSet.isEmpty(PersistentSet.java:166) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
        at com.midi.samples.petclinic.model.Zone.getLocationsInternal(Zone.java:41) ~[classes/:na]
        at com.midi.samples.petclinic.model.Zone.addLocation(Zone.java:55) ~[classes/:na]
        at com.midi.samples.petclinic.web.LocationController.initCreateForm(LocationController.java:52) ~[classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
```

**Comment by midikang** [comment]
Change query in SDZoneRep interface
- Before

```
    @Query("SELECT zone from Zone zone where zone.id= :id")
    Zone findById(@Param("id") int id) throws DataAccessException;
```
- After

```
    @Query("SELECT zone from Zone zone left join fetch zone.locations where zone.id= :id")
    Zone findById(@Param("id") int id) throws DataAccessException;
```
